version: "2"
services:
  core:
    working_dir: /app/core
    build:
      context: core/
    volumes:
      - ./:/app
    environment:
      PIPENV_VENV_IN_PROJECT: "true"
  api:
    build:
      context: api/
    volumes:
      - ./api:/app
    ports:
      - "80:3000"