name: Python CI

on:
    push:
      branches: [ main ]
    workflow_dispatch:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.1', '3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        cd core/ && echo 'PYTHONPATH=${PYTHONPATH}:${PWD}' >> .env
        cd core/ && pip install --upgrade pip
        cd core/ && pip install pipenv
        cd core/ && pipenv install
        cd core/ && pipenv install --dev
        cd core/ && pipenv run pytest
