name: Python CI

on:
    push:
      branches: [ main ]
    workflow_dispatch:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.1', '3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        cd core/
        echo 'PYTHONPATH=${PYTHONPATH}:${PWD}' >> .env
        pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv install --dev
        pipenv run pytest
